language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t park-api-user ./api-user
  - docker build -t park-api-car ./api-car
  - docker build -t reverse-proxy ./reverse-proxy
  - docker tag reverse-proxy officialphemi/reverse-proxy
  - docker tag park-api-user officialphemi/park-api-user
  - docker tag park-api-car officialphemi/park-api-car

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push officialphemi/park-api-user
  - docker push officialphemi/park-api-car
  - docker push officialphemi/reverse-proxy