version: "3"
services:
  reverse_proxy:
    build:
      context: ./reverse-proxy
    image: reverse-proxy
  backend_user:
    build:
      context: ./api-user
    image: park-api-user
  backend_car:
    build:
      context: ./api-car
    image: park-api-car
  backend_parking:
    build:
      context: ./api-parkings
    image: park-api-parkings