version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: 
          name: "Run test"
          command: | 
            echo "no tests"
  build_and_deploy: 
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: 
          name: "Build and tag images"
          command: |
            echo 'export BUILD_VERSION=$CIRCLE_BUILD_NUM' >> $BASH_ENV
            source $BASH_ENV
            docker --version 
            docker build -t park-api-user ./api-user
            docker build -t park-api-car ./api-car
            docker build -t park-api-parkings ./api-parkings
            docker build -t reverse-proxy ./reverse-proxy
            docker tag reverse-proxy officialphemi/reverse-proxy:v"$CIRCLE_BUILD_NUM"
            docker tag park-api-user officialphemi/park-api-user:v"$CIRCLE_BUILD_NUM"
            docker tag park-api-car officialphemi/park-api-car:v"$CIRCLE_BUILD_NUM"
            docker tag park-api-car officialphemi/park-api-parkings:v"$CIRCLE_BUILD_NUM"
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push officialphemi/park-api-user:v"$CIRCLE_BUILD_NUM"
            docker push officialphemi/park-api-car:v"$CIRCLE_BUILD_NUM"
            docker push officialphemi/park-api-parkings:v"$CIRCLE_BUILD_NUM"
            docker push officialphemi/reverse-proxy:v"$CIRCLE_BUILD_NUM"
workflows:
  scripts:
    jobs:
      - test
      - build_and_deploy
