version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  test:
    docker:
      - image: circleci/docker@1.5.0
    steps:
      - checkout
      - run: echo "no tests"
  build: 
    docker:
      - image: circleci/docker@1.5.0
    steps:
      - checkout
      - run: docker --version # print the version for logging
      - run: docker build -t park-api-user ./api-user
      - run: docker build -t park-api-car ./api-car
      - run: docker build -t reverse-proxy ./reverse-proxy
      - run: docker tag reverse-proxy officialphemi/reverse-proxy
      - run: docker tag park-api-user officialphemi/park-api-user
      - run: docker tag park-api-car officialphemi/park-api-car
  deploy:
    docker:
      - image: circleci/docker@1.5.0
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: docker push officialphemi/park-api-user
      - run: docker push officialphemi/park-api-car
      - run: docker push officialphemi/reverse-proxy
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy
      
